server.port=8081

# SQLite Auth Database Connection
spring.datasource.url=jdbc:sqlite:auth_service.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# JPA / Hibernate Configuration
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT Token Secret Key
app.jwt.secret=CareerPlusSuperSecretKey2026AuthenticationMicroserviceSecure987654321
app.jwt.expiration-ms=86400000
